In [2]:
import numpy as np

In [3]:
minha_lista = [1, 2, 3, 4]

In [4]:
minha_lista

[1, 2, 3, 4]

In [5]:
np.array(minha_lista)

array([1, 2, 3, 4])

In [8]:
minha_matriz = [[1, 2, 3], [4, 5, 6,], [7, 8, 9,]]

In [9]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
arr = np.zeros(3)

In [14]:
arr

array([0., 0., 0.])

In [15]:
arr = np.zeros((5, 5))

In [16]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [20]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [24]:
np.random.rand(5)

array([0.20671009, 0.19495364, 0.57614169, 0.71424787, 0.58450755])

In [25]:
np.random.rand(5) * 100

array([61.06203752, 12.34740787, 48.7787305 , 93.87600095, 15.26682324])

In [27]:
np.random.rand(5, 4)

array([[0.09717386, 0.12906727, 0.27640951, 0.71510478],
       [0.79634412, 0.57838618, 0.16665257, 0.49556091],
       [0.78006953, 0.07784965, 0.94683327, 0.81456566],
       [0.51091608, 0.25783157, 0.38954261, 0.04617867],
       [0.6820429 , 0.23791967, 0.75328688, 0.16527298]])

In [29]:
np.random.rand(5, 4, 3)

array([[[0.96961052, 0.34434118, 0.14876474],
        [0.56880078, 0.07685788, 0.73226009],
        [0.00342312, 0.80768588, 0.00111321],
        [0.62249214, 0.64869466, 0.98011305]],

       [[0.92858349, 0.26722733, 0.85114367],
        [0.05033798, 0.31175827, 0.37591386],
        [0.32051537, 0.19588421, 0.93649439],
        [0.44313298, 0.02313087, 0.27269548]],

       [[0.5777871 , 0.79202919, 0.71102795],
        [0.74441834, 0.60831896, 0.01082924],
        [0.30079115, 0.77812418, 0.87571812],
        [0.8274246 , 0.60380398, 0.62449657]],

       [[0.52882193, 0.92884579, 0.00600878],
        [0.6467322 , 0.50411499, 0.11623674],
        [0.48627816, 0.63912415, 0.15631053],
        [0.22443201, 0.42859539, 0.59863095]],

       [[0.49672855, 0.22249192, 0.12887927],
        [0.60854016, 0.43130283, 0.79654766],
        [0.08380998, 0.84476347, 0.09539612],
        [0.00144094, 0.8770315 , 0.38977455]]])

In [30]:
np.random.randn(4)

array([ 0.23876441, -0.68175053,  2.52787186, -0.75871072])

In [31]:
np.random.randint(0 ,100, 10)

array([40, 42, 58,  2, 99, 17, 40, 10, 11, 64])

In [32]:
np.round(np.random.rand(5) * 100, 0)

array([ 9., 75., 74.,  9., 12.])

In [33]:
arr = np.random.rand(25)

In [34]:
arr

array([0.52706931, 0.95236541, 0.81863074, 0.29072403, 0.81182183,
       0.35248864, 0.7479627 , 0.57303859, 0.90297482, 0.39540587,
       0.14031109, 0.98210207, 0.1096287 , 0.32130006, 0.75019242,
       0.89407325, 0.17678345, 0.28495325, 0.55501821, 0.67355376,
       0.49188058, 0.23300771, 0.73881277, 0.61838589, 0.56570176])

In [35]:
arr.reshape((5, 5))

array([[0.52706931, 0.95236541, 0.81863074, 0.29072403, 0.81182183],
       [0.35248864, 0.7479627 , 0.57303859, 0.90297482, 0.39540587],
       [0.14031109, 0.98210207, 0.1096287 , 0.32130006, 0.75019242],
       [0.89407325, 0.17678345, 0.28495325, 0.55501821, 0.67355376],
       [0.49188058, 0.23300771, 0.73881277, 0.61838589, 0.56570176]])

In [37]:
arr = arr.reshape((5, 5))

In [38]:
arr

array([[0.52706931, 0.95236541, 0.81863074, 0.29072403, 0.81182183],
       [0.35248864, 0.7479627 , 0.57303859, 0.90297482, 0.39540587],
       [0.14031109, 0.98210207, 0.1096287 , 0.32130006, 0.75019242],
       [0.89407325, 0.17678345, 0.28495325, 0.55501821, 0.67355376],
       [0.49188058, 0.23300771, 0.73881277, 0.61838589, 0.56570176]])

In [39]:
arr.shape

(5, 5)

In [40]:
arr.max()

0.9821020676597206

In [41]:
arr.min()

0.10962870403979263

In [42]:
arr.argmax()

11

In [46]:
arr[2][1]

0.9821020676597206

In [47]:
arr.argmin()

12

In [48]:
arr[2][2]

0.10962870403979263